### ISSUE TITLE
Turkish Language

### ISSUE THREAD

**Issue by lem0n4de** [AnySoftKeyboard/LanguagePack#112] opened 2017-12-15 04:53 UTC
Hello,
As there is no Turkish language pack for ASK, i made one somehow. There is this problem; 

Turkish has 2 "i" letter, with a dot[i] and without it[ı]. When we create a layout with these and try to write in capitals, both letter becomes [I]. This is the default capital for [i] in English but in Turkish [i] becomes [İ] and [ı] becomes [I].

Here is a Wikipedia webpage about the problem:
https://en.wikipedia.org/wiki/Turkish_dotted_and_dotless_I

So what I am asking is: Is there a way to change the capitals for a layout (I could not find any) or how can we avoid this?

**Comment by BoFFire** [comment] 2017-12-15 09:13
Hello @Sixthtry,
I think that you have to focus on the Unicode first :
_U+0130_  = LATIN CAPITAL LETTER I WITH DOT ABOVE = İ
Wich has as lower case _U+0069_  = LATIN SMALL LETTER I = i
You have now to convert both to the right decimal on the keyboard starting with the small letter i.
Wainting for an answer.
Regards,

**Comment by Sixthtry** [comment] 2017-12-15 20:26
Hi @BoFFire,
In the layout, I have both Latin Small Letter I, which is [ i ] and unicode "105", and Latin Small Letter Dotless I, which is [ ı ] and unicode 305. Both works well when writing in lowercase. 

The problem is, when I turn on the uppercase writing, dotless little i with unicode 305 should turn to "LATIN CAPITAL LETTER I", which is [ İ ] and unicode 304 but instead it becomes "LATIN CAPITAL LETTER I", which is [ I ] and unicode 73. 

(Sorry for being late. I wrote an answer on phone but git client got crashed.)

**Comment by menny** [comment] 2017-12-15 20:30
@Sixthtry you can use `ask:shiftCodes` to specify special uppercase codes, in case the automatic guessing fails

**Comment by Sixthtry** [comment] 2017-12-15 22:51
That was just what I needed for. Thank you very much sir. And may I ask you to open up a Turkish branch? I am trying to build a nice dictionary and then I will try to upload files here somehow (I am new to the Git).

**Comment by menny** [comment] 2017-12-15 23:35
Done: https://github.com/AnySoftKeyboard/LanguagePack/tree/Turkish
Please make sure your branch is rebased on top latest https://github.com/AnySoftKeyboard/LanguagePack/tree/Turkish, and that you point your PR to my `Turkish` branch.

Also, how are you creating the dictionary?

**Comment by Sixthtry** [comment] 2017-12-16 05:00
As I saw from a thread in here, "New Sicilian language pack" thread to be exact, I am collecting wikipedia pages. I also did WordsfromAosp but this is all I know about dictionaries.

**Comment by menny** [comment] 2017-12-16 05:11
These are both very good sources. I mostly wanted to make sure that you are
aware of them, and that the sources you are using are not copyrighted in
any restricted way.

**Comment by Sixthtry** [comment] 2017-12-17 07:09
Hey, umm,
I was trying to get as many pages as I can in Turkish manually yesterday. Today I realized that there is dump of wikipedia as said in build.gradle comments [(.](https://dumps.wikimedia.org/other/static_html_dumps/current) I downloaded the one for Turkish, it was around 300 MB but it extracted as 6.8 GB .tar file. Now there is .html's inside this but they are in files and I don't know how can I put them in build.gradle. 

Also I found another file in wikimedia dumps. It is in [https://dumps.wikimedia.org/trwikisource/20171201/](url) and there is an .xml (trwikisource-20171201-pages-articles.xml.bz2) file which contains "Articles, templates, media/file descriptions, and primary meta-pages" as title says in a file which is 70 MB after extract.

I am wondering, what I will get from these two files will be the same? 

[I am sorry that I am asking a lot of questions, but I am doing this for the first time and I want it to be usable enough.]

**Comment by menny** [comment] 2017-12-17 16:20
Wiki dumps are good, but there are two general problems with them:
1. They include words in other languages, which sometime get added to the generated dictionary
2. They are not "dialog“ source, so the word frequency might seem strange

**Comment by Sixthtry** [comment] 2017-12-18 16:34
I gave up on aosp word list as it just does not generate any wordlist. I can see that it is a long file in editor but I can not read of course but the code can't either. The parseAospForEnglishDictionary task generates a 2 line file from that which contains only;  `</wordlist> `

**Comment by menny** [comment] 2017-12-18 17:11
@Sixthtry can you send me a link to that aosp file?

**Comment by menny** [comment] 2017-12-18 17:16
Also, you'll need to fix/complete the issues reported here: https://271-4270172-gh.circle-artifacts.com/0/lint_reports/app/checkstyle/checkstyle.html

**Comment by Sixthtry** [comment] 2017-12-18 17:42
[https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/master/dictionaries/tr_wordlist.combined.gz](url) Here is the aosp wordlist link. I downloaded it from the `[txt]` link in the right corner

**Comment by menny** [comment] 2017-12-19 03:46
I see. This is how to get the real gz file. First, clone the repo to your local machine:
`git clone https://android.googlesource.com/platform/packages/inputmethods/LatinIME`
then `cd` to the dictionaries folder:
`cd LatinIME/dictionaries`
find the Turkish dictionary `tr_wordlist.combined.gz` (it's 926338 bytes), and unzip it. Use the uncompressed file as the input for `parseAospForEnglishDictionary`

**Comment by Sixthtry** [comment] 2017-12-20 20:00
Thank you for being so helpful, that solved the problem. I want to ask just one last question; Is there a document where I can find all `ask:` and `android: `codes?

**Comment by menny** [comment] 2017-12-20 20:14
Glad it helped! Can't wait to see the new language pack 👍

Regarding attributes, you can check the source code of AnysoftKeyboard API,
and specifically, the styleables:
https://github.com/AnySoftKeyboard/AnySoftKeyboard-API/blob/master/api/src/main/res/values/keyboard_layout_api.xml

**Comment by MK8T** [comment] 2017-12-29 15:15
I dont see the  ask:shiftCodes to specify special uppercase codes 
in https://github.com/AnySoftKeyboard/LanguagePack/blob/Turkish/src/main/res/xml/qwerty.xml  ... perhaps dont read the good file ?

**Comment by Sixthtry** [comment] 2017-12-29 17:15
@MK8T
Okay, sorry for that but there seems to be a problem with file. I will reupload it to github manually then, it works in my keyboard.

**Comment by Sixthtry** [comment] 2017-12-30 06:17
@MK8T 
Oh, I understand now. You are looking at the 'Turkish' branch of original AnySoftKeyboard repo. My repo did not merged yet with it. You should look at here = [https://github.com/Sixthtry/LanguagePack/blob/master/src/main/res/xml/qwerty.xml](url)

**Comment by friesenkiwi** [comment] 2018-02-25 12:48
Closing this in favor of #116

**Closed by friesenkiwi** 2018-02-25 12:48 UTC
