### ISSUE TITLE
German: Holding U does not default to Ü

### ISSUE THREAD

**Issue by mueller-ma** [AnySoftKeyboard/LanguagePack#63] opened 2017-06-04 18:26 UTC
I'm using German broad +. When I hold U the default sign is a U with ´´ on top.

**Comment by friesenkiwi** [comment] 2017-07-10 09:57
I can confirm this on my device, see screenshots below.

The problem seems to be, that for o (`android:popupCharacters="ö9òóôõøőœō"`) it is a 2-row popup while it is 1-row for u (`android:popupCharacters="ü7ùúûŭűū"`).
@menny do you think this could be fixed for the general case?
A "hack" or workaround might be to add one ore two characters more (maybe see https://en.wikipedia.org/wiki/U#Ancestors.2C_descendants_and_siblings) to the u popup to turn it into a 2-row one which should then behave like o's

![kur6xvg7rscwn1y9bwgp7g_2bfeb8dd898aadc90d5ad7331b0a2f652b986544](https://user-images.githubusercontent.com/13440054/28012321-b34da4e2-6565-11e7-837e-374629ed30dc.jpg)
![d7jbit0ureoro-kjqyijia_22132fe3e7e0151fe6ead257f3d2eac65fbea60a](https://user-images.githubusercontent.com/13440054/28012322-b35a0f34-6565-11e7-85c9-d41d2282a71c.jpg)

**Comment by friesenkiwi** [comment] 2017-07-23 22:45
Closed via #76

**Closed by friesenkiwi** 2017-07-23 22:45 UTC
Labels: bug
