### ISSUE TITLE
Lithuanian language pack no longer on Google Play

### ISSUE THREAD

**Issue by SauBabas** [AnySoftKeyboard/LanguagePack#193] opened 2018-12-02 15:41 UTC
There isn't available to download lithuanian language pack on Playstore. I remember, there always was that pack, but for quite long time it's gone.

**Comment by rimas-kudelis** [comment] 2019-04-04 07:15
This is a duplicate of #168. The pack is now resurrected, and we're working on transitioning its ownership.

**Closed** 2019-04-04 16:13 UTC
